### ISSUE TITLE
NewClient incorrectly sets Host to "localhost"

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Rumba#16]
https://github.com/the-carlisle-group/Rumba/blob/4fe89e8e2e0429bee7d2341af12840512ac8e62e/APLSource/Core-1/NewClient-9.aplf#L7

The help states that NewClient.Host will be set automatically if not set and the value will be derived from Request.URI

**Comment by norberturkiewicz** [comment]
@PaulMansour,  should the help be changed to state that Client.Host defaults to 'localhost' and does not obtain a default host from Request.URI?   The help will need to change the correct format of Request.URI is only the path portion of the URL.

**Comment by aplteam** [comment]
It was me who came up with the idea to extract the domain name from the URI (if it carries one) and assign it to the "Host" field when that is empty.

The reason was that GitHub returns a 301 in case one does not set "Host" and the URI is something like "github.com/{owner}/{project} which looks kind of stupid.

Because Paul agreed on that I changed the help page and wanted to change the code next but then changed my mind. It think that "localhost" is a good default, and there is no need for a change.

I therefore suggest to replace the following sentence on the help page related to the "Host" property:
`If the property is not set Rumba will extract the host name from the URL.`
by
`This property defaults to "localhost"`

That how is was all the time, and nobody objected.

May I leave this with you Norbert?

**Comment by norberturkiewicz** [comment]
Done.
